services:
  backend:
    build: ./backend
    networks:
      - app-network

  webserver:
    build: ./webserver
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge